version: "3.9"

services:
  auth:
    image: go-auth-api:latest
    ports:
      - "9999:9999"
    environment:
      DB_DRIVER: mysql
      DB_USER: user
      DB_PASS: password
      DB_NAME: db
      DB_HOST: dbserver
      DB_PORT: 3306
      TOKEN_HOUR_LIFESPAN: 1
      API_SECRET: D990D249-BD92-41C2-A0CC-FEFD2901D1AB
      WEB_SERVER: "127.0.0.1"
      WEB_SERVER_ORIGIN: "http://127.0.0.1"
      WEB_SERVER_ORIGIN_LOCAL: "http://127.0.0.1:3000"
    depends_on:
      dbserver:
        condition: service_healthy
    restart: always

  dbserver:
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
    restart: always

  webserver:
    image: nginx:1.25
    ports:
      - "80:80"
    restart: always
    volumes:
      #- ./out:/app_dir
      - ./webserver/nginx_conf:/etc/nginx/conf.d
      - ./webserver/nginx_document:/var/www/html
